version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test
      - setup_remote_docker
      - run:
          name: Deploy all connectors
          command: |
            base64 --decode $DEPLOYMENT_CONFIG_JS > deployment.config.js
            BRANCH=$CIRCLE_BRANCH
            CONNECTORS=`sh scripts/get-connectors-to-deploy.sh`
            echo $CONNECTORS
