version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:8.12
    steps:
      - run:
          name: Run tests
          command: yarn test
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - setup_remote_docker
      - run:
          name: Deploy all connectors
          command: |
            base64 --decode $DEPLOYMENT_CONFIG_JS > deployment.config.js
            BRANCH=$CIRCLE_BRANCH
            CONNECTORS=`sh scripts/get-connectors-to-deploy.sh`
            echo $CONNECTORS
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
          filters:
            branches:
              only:
                - master
                - develop
